
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

pagination.pageSize = 20

# base front end url
frontend.url=http://localhost:3000

# Paypal
# PayPal Sandbox Credentials
paypal.client-id=AXujFaxeceDT48jTPIqlyYqRfmD4CFzDnV73vxKILW4Du8eF15iCN7IkjkmO_zlBFGRqokqhzazBpmz6
paypal.secret=EAV8DEM2JwOLG6GJSUQckJ8G9Ehy991kfmveHd6NBpB34lVFJZ4XIdXJyiltVH4O0btnWWyOVjcuYnsQ
paypal.mode=sandbox
paypal.base-url=https://api-m.sandbox.paypal.com

paypal.cancel-url=http://localhost:8080/nvtt_lqv/api/v1/public/payment/paypal/cancel
paypal.return-url=http://localhost:8080/nvtt_lqv/api/v1/public/payment/paypal/success

#config send email by Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vthanhtrongng@gmail.com
spring.mail.password=qimfdkcwfrcpfbjw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
